services:
  - type: web
    name: irts-parcoursup
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build:front
    startCommand: node server/api-simple.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
